---
name: Build & Release
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
      - uses: actions/checkout@v4
      - name: "Run image builder dependency"
        run: "sh install.sh"
      - name: "Building scratch image"
        run: "sh build-image.sh"