---
name: Build & Release
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rockylinux-job:
    runs-on: ubuntu-latest
    container: 
        image: rockylinux:8
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: "Run image builder dependency"
        run: "sh install.sh"
      - name: "Building scratch image"
        run: "sh build-image.sh"
      - uses: actions/upload-artifact@v3
        with:
          name: rockylinux8-docker.tar.xz
          path: /var/tmp/rockylinux8-docker.tar.xz