---
name: Build & Release
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - uses: actions/checkout@v4
      - name: "Run image builder"
        run: "sh install.sh"